spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/spring_db?useSSL=false&characterEncoding=utf-8
      username: root
      password: 1234